### PR TITLE
SearchQueryBuilder for sonar-client

### PR DESCRIPTION
**Pull request by hng**
Started work on QueryBuilder class for sonar-client. Still work in progress, don't merge.

### CODE REVIEW

**Comment by hng** [comment]
Although the SearchQueryBuilder only supports bool and phrase searches now I think we should merge it as it provides a new structure for sonar-client that shouldn't diverge from master any longer

**Comment by Frando** [comment]
Looks good i think. Will try to review properly tonight or tomorrow.

for now a question: are nested queries supported? So (phrase x) OR (term y)? I think our tantivy backend should support it. Doesnt have to be supported by the client for now but lets keep it in mind while designing the api.

oh and code style seems to be off, can you configure your editor to use the https://standardjs.com style? Can also fix this after merge for now.

**Comment by Frando** [comment]
Merged in master and fixed the conflicts.

**Comment by Frando** [comment]
I fixed the code style issues and did a little little bit of cleanup, no functional changes. I will merge this in now, even though I think the API will need a little bit more of discussion. I'll open an issue for that, but merge now anyway because all tests pass and things will get more difficult otherwise.

**Comment by Frando** [comment]
Hooray, all merged! :100: :fireworks:

**Pull request merged**
